### ISSUE TITLE
Show Image

### ISSUE THREAD

**Issue by haivipreal** [jlord/sheetsee.js#128]
Dear Jlord,

The sheetsee script is so great to show image gallery pulling from google sheet. I have used this script over a year in blogspot but I found it in trouble a weak ago. It look like new version of sheetsee does not support to show image from google sheet. Please help me to advise or give me the old version one. Tks much.

My website: http://www.miaorder.com/p/ban.html. 
https://productforums.google.com/forum/#!topic/blogger/muwd1GF34tw

**Comment by dx76** [comment]
I am very sorry to hear that is that something I did wrong and I am not aware of I want to fix this if I can thank you very much respectfully Brent Dixon

**Comment by jlord** [comment]
> It look like new version of sheetsee does not support to show image from google sheet

This isn't specifically the case, it's that the Sheetsee API and dependencies have changed. 

You can find the old version from this [issue comment](https://github.com/jlord/sheetsee.js/issues/127#issuecomment-291889035) but you should copy this file and have it local to your site rather than linking to the version in this repository which will change as Sheetsee changes.
