### ISSUE TITLE
[Question] How can I use json as data source?

### ISSUE THREAD

**Issue by johndezember** [jlord/sheetsee.js#150]
Hi, thanks for making sheetsee.js! It is great!
How can I use a json url for the data source (instead of a Google Sheet)?
Thanks

**Comment by mrisad504** [comment]
instead of a Google Sheet

**Comment by jlord** [comment]
Hi! Yes, you can definitely use JSON instead of a google spreadsheet. You just need to make that JSON available to pass into Sheetsee methods.

I have done this with a page I made: [jlord.us/vermeer](http://jlord.us/vermeer)

Data is `data.json` where I set all the data to a variable: https://github.com/jlord/vermeer/blob/gh-pages/assets/data.json

In my `index.html` bring in that file: https://github.com/jlord/vermeer/blob/gh-pages/index.html#L19

Then use the global variable directly to pass into Sheetsee: https://github.com/jlord/vermeer/blob/gh-pages/index.html#L90

There are probably better ways to do it, but this is the easy way I've been using. Hope that helps!
